version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: savings_mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - /Users/miguel.calvo/techdemos/modernbank/volumes/storage/savings/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped