version: '3'

services:

  consul-server-bootstrap:
    image: consul:latest
    networks:
      - consul-network
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

  consul-server-1:
    image: consul:latest
    networks:
      - consul-network
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    image: consul:latest
    networks:
      - consul-network
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

networks:
  consul-network:
